/** @type {import('next').NextConfig} */
// build-cache-bust: 2026-02-25
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  output: 'standalone',
  // Skip generating static error pages
  experimental: {
    serverComponentsExternalPackages: ['@sparticuz/chromium', 'puppeteer-core'],
    skipTrailingSlashRedirect: true,
  },
  eslint: {
    // Temporarily ignore ESLint during `next build` to avoid flooding build logs
    // with pre-existing @typescript-eslint warnings. Lint should run in CI and
    // in local pre-commit hooks (see `pnpm lint:ci` / `pnpm lint:full`).
    ignoreDuringBuilds: true,
    dirs: [],
  },
  typescript: {
    // Type errors in __tests__/ and docs/testing/ are pre-existing and excluded
    // from tsconfig.json's exclude list — they don't affect production code.
    // Production type safety is enforced via `pnpm type-check` and CI.
    ignoreBuildErrors: true,
  },
  images: {
    domains: ['www.gov.br'],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'www.gov.br',
        port: '',
        pathname: '/**',
      },
    ],
  },
  async redirects() {
    return [
      {
        source: '/termos/contrato-padrao',
        destination: '/termos/contrato',
        permanent: true,
      },
    ];
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=31536000; includeSubDomains',
          },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=()' },
        ],
      },
    ];
  },
  // Fix: Node.js 22+ + Edge Runtime rejects eval() generated by webpack.
  // The Edge Runtime sandbox (node:vm) is created with
  // contextCodeGeneration.strings=false, which blocks all eval().
  // 
  // Solution: Disable source maps globally and in edge runtime.
  // The Next.js middleware-loader generates eval() with inline source maps
  // which triggers EvalError. Disabling all source maps prevents this.
  productionBrowserSourceMaps: false,
  webpack(config, { dev, nextRuntime }) {
    // Disable source maps for all runtime contexts to prevent eval()
    config.devtool = false;
    
    // Force options.sourceMap = false on all loaders
    if (config.module?.rules) {
      for (const rule of config.module.rules) {
        if (rule.use && Array.isArray(rule.use)) {
          for (const loader of rule.use) {
            if (typeof loader === 'object' && loader.options) {
              loader.options.sourceMap = false;
            }
          }
        } else if (rule.use && typeof rule.use === 'object') {
          if (rule.use.options) {
            rule.use.options.sourceMap = false;
          }
        }
      }
    }
    return config;
  },
};

module.exports = nextConfig;
