/** @type {import('next').NextConfig} */
// build-cache-bust: 2026-02-25
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  output: 'standalone',
  // Skip generating static error pages
  experimental: {
    serverComponentsExternalPackages: ['@sparticuz/chromium', 'puppeteer-core'],
    skipTrailingSlashRedirect: true,
  },
  eslint: {
    // Temporarily ignore ESLint during `next build` to avoid flooding build logs
    // with pre-existing @typescript-eslint warnings. Lint should run in CI and
    // in local pre-commit hooks (see `pnpm lint:ci` / `pnpm lint:full`).
    ignoreDuringBuilds: true,
    dirs: [],
  },
  typescript: {
    // Type errors in __tests__/ and docs/testing/ are pre-existing and excluded
    // from tsconfig.json's exclude list — they don't affect production code.
    // Production type safety is enforced via `pnpm type-check` and CI.
    ignoreBuildErrors: true,
  },
  images: {
    domains: ['www.gov.br'],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'www.gov.br',
        port: '',
        pathname: '/**',
      },
    ],
  },
  async redirects() {
    return [
      {
        source: '/termos/contrato-padrao',
        destination: '/termos/contrato',
        permanent: true,
      },
    ];
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=31536000; includeSubDomains',
          },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=()' },
        ],
      },
    ];
  },
  // Fix: Node.js 22+ + Edge Runtime rejects eval() generated by webpack's
  // eval-source-map devtool. In dev mode Next.js defaults to 'eval-source-map'
  // which causes EvalError inside the Edge Runtime VM sandbox.
  // Use 'cheap-source-map' (eval-free) in dev and false in prod.
  webpack(config, { dev, nextRuntime }) {
    if (nextRuntime === 'edge') {
      config.devtool = dev ? 'cheap-source-map' : false;
    }
    return config;
  },
};

module.exports = nextConfig;
