--
-- PostgreSQL database dump
--

-- Dumped from database version 17.8 (a48d9ca)
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: empresas_clientes; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (5, 'Empresa CM onlinwe', '22902898000126', '55asds@dsdssdf.com', '(46) 54654-6566', 'rua lkj lk 89089', 'ipiopipo', 'IO', '45612456', true, 104, '2026-02-10 09:40:21.970549', '2026-02-10 09:40:21.970549', 'dsdsd dfssfdf', '46465456456', 'fssafsf@fasasf.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (6, 'Empresa clin fina 001', '82429448000190', 'sdfsdf@assa.com', '(45) 64546-6545', 'Rua Antônio Bianchetti, 90', 'São José dos Pinhais', 'FE', '83065-370', true, 107, '2026-02-11 01:52:11.752978', '2026-02-11 01:52:11.752978', 'GEstor CLun fianl', '89798798799', 'rerewewr@fdsfds.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (7, 'TESTE EMPRESA', '05073619000140', 'DFFJKJHDKLGDF@GMAIL.COM', '(06) 84680-4804', 'Barão do Serro Azul, 198 - Centro', '3946', 'PR', '80020-180', true, 108, '2026-02-12 12:15:27.394911', '2026-02-12 12:15:27.394911', 'TESTE GESTOR EMPRESA', '50465046504', '506068FGFD@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (8, 'Empasa Amada Aeso', '16122856000170', 'dffds@afaf.com', '(46) 54897-9879', 'rrpoiop poipo  123', 'uiou iioi', 'IO', '45678456', true, 109, '2026-02-12 18:32:10.507968', '2026-02-12 18:32:10.507968', 'Amanda Acesso', '45646546546', 'dfdsf@dsffds.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (9, 'Empresa RH da clini', '91105132000133', 'sdsds@dfdf.com', '(45) 46545-6465', 'Rua Antônio Bianchetti, 90', 'São José dos Pinhais', 'PR', '83065-370', true, 111, '2026-02-13 02:51:46.972587', '2026-02-13 02:51:46.972587', 'GEsto RH final', '45478878877', 'sds@xcxcx.om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (10, 'TESTE TESTE', '43627564000161', NULL, NULL, NULL, NULL, NULL, NULL, true, 112, '2026-02-16 14:31:27.053862', '2026-02-16 14:31:27.053862', 'TESTE TESTE', '60884086400', 'FGKDFGHDF@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (11, 'Empresa Clin Amanda Ltda', '54223491000169', 'dfdsf@afa.com', '(46) 54564-6546', 'rua opoipo 234', 'iopiopipi', 'IO', '45678456', true, 112, '2026-02-16 17:43:31.4948', '2026-02-16 17:43:31.4948', 'Tste 1602 clin', '98465465465', 'fddfs@sdfsdf.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (12, 'GEsor Clinex', '32375691000102', 'sdfsdf@sadsad.com', '(54) 65465-4656', 'rua pipoi o3553', 'sfaasf', 'OP', '454612456', true, 113, '2026-02-16 18:27:01.456567', '2026-02-16 18:27:01.456567', 'Amnada Gestora', '46546546546', 'dfdsf@dsfsdf.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (13, 'Empresa Clinica End', '00790746000146', 'dsfsdf@sadffas.com', '(46) 45646-5466', 'rua ljlko 908098', 'fdsdd', 'OP', '45612789', true, 115, '2026-02-17 16:15:34.199728', '2026-02-17 16:15:34.199728', 'Romalo fdoipoipo', '77464654666', 'dsfdsf@dsfdsf.co', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (14, 'Empres clin 02', '40337270000107', 'cffas@sfddsf.oj', '(65) 46545-6465', 'rua ljijio 890', 'ddsfd', 'PO', '45612456', true, 104, '2026-02-17 19:30:08.900293', '2026-02-17 19:30:08.900293', 'Robero pipoipoi', '64546546546', '46545@dfsfd.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (15, 'Emp cline 2026 fev', '16285851000168', 'fdsdsfsdf@dsfdsf.com', '(79) 79798-7746', 'rua idsfpoi 2345', 'eewefdssdfsdf', 'OP', '78945456', true, 118, '2026-02-23 22:46:28.302503', '2026-02-23 22:46:28.302503', 'Rona Fialrdo', '49879879879', 'ronsadlf@fdfd.com', NULL, 'https://s3.us-east-005.backblazeb2.com/laudos-qwork/cad-qwork/16285851000168/cartao_cnpj-1771886783385-3y7mu4.pdf', 'https://s3.us-east-005.backblazeb2.com/laudos-qwork/cad-qwork/16285851000168/contrato_social-1771886787397-9iogcq.pdf', 'https://s3.us-east-005.backblazeb2.com/laudos-qwork/cad-qwork/16285851000168/doc_identificacao-1771886787566-jpzqs5.pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (16, 'fdfds sdfdfssfd', '79973255000190', 'dsdsfsf@fdssd.com', '(78) 97987-9879', 'rua podsipo 23423', 'uiouoiuoi', 'UI', '45678456', true, 119, '2026-02-25 16:02:54.251984', '2026-02-25 16:02:54.251984', 'rnapdop dfiop po', '54465465466', 'fddsf@fdsdsf.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (17, 'dfsgsG SDFsfes', '33671387000167', NULL, NULL, NULL, NULL, NULL, NULL, true, 120, '2026-02-25 18:04:58.534983', '2026-02-25 18:04:58.534983', 'sjkdfhkjsd hjkfdsh fjk hsdkj', '80740840684', 'sdfDFDBKA@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (18, 'emeoa ruao io', '88804016000106', 'ewewwe@aaf.scom', '(48) 64546-4654', 'rua ouiou 342', 'uiouoiuoi', 'UI', '45678456', true, 123, '2026-02-27 13:18:11.481166', '2026-02-27 13:18:11.481166', 'rei po p', '47777795645', 'fdfds@sddsfa.ciu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (19, 'empre pos revad 01', '67394465000145', 'fdsdf@fafas.com', '(46) 57987-9879', 'rua pipoi rew 890', 'lopipoi', 'IO', '45645456', true, 128, '2026-03-08 01:12:48.260373', '2026-03-08 01:12:48.260373', 'rh 01 por refacr', '41998798897', 'iyi@guuyu.cou', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (20, 'Farma Mori', '33447623000166', 'farmamori@mori.com', '(41) 99984-6465', 'rua cur4iiba 456', 'ctba', 'PR', '45678465', true, 129, '2026-03-09 01:55:13.380677', '2026-03-09 01:55:13.380677', 'Gestor MedCtba', '41321321323', 'medctba@med.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (21, 'Construtora Teste Ltda', '46998507000187', 'conta@costr.com', '(41) 54654-6546', 'Rua da Obra, 123', 'Curitiba', 'PR', '45678465', true, 131, '2026-03-16 13:11:01.409387', '2026-03-16 13:11:01.409387', 'Contato Empresa testes', '41945646546', 'contao@emre.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (22, 'Med Curitiba', '30615448000180', NULL, NULL, NULL, NULL, NULL, NULL, true, 129, '2026-03-16 17:49:30.97302', '2026-03-16 17:49:30.97302', 'Ludimila Pereira', '41992342929', 'psicossocial@medcuritiba.com.br', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (23, 'CONSTRUTORA INOVA AGORA', '17383721000120', NULL, NULL, NULL, NULL, NULL, NULL, true, 120, '2026-03-26 18:13:57.306902', '2026-03-26 18:13:57.306902', 'GILSON SDFSDF', '60840684684', 'DDHFJHG@GMAIL.COM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.empresas_clientes (id, nome, cnpj, email, telefone, endereco, cidade, estado, cep, ativa, clinica_id, criado_em, atualizado_em, representante_nome, representante_fone, representante_email, responsavel_email, cartao_cnpj_path, contrato_social_path, doc_identificacao_path, cartao_cnpj_arquivo_remoto_provider, cartao_cnpj_arquivo_remoto_bucket, cartao_cnpj_arquivo_remoto_key, cartao_cnpj_arquivo_remoto_url, contrato_social_arquivo_remoto_provider, contrato_social_arquivo_remoto_bucket, contrato_social_arquivo_remoto_key, contrato_social_arquivo_remoto_url, doc_identificacao_arquivo_remoto_provider, doc_identificacao_arquivo_remoto_bucket, doc_identificacao_arquivo_remoto_key, doc_identificacao_arquivo_remoto_url) VALUES (24, 'B&B pães e doçes', '64543601000123', 'fabricacao@gmail.com', '(11) 98512-8525', 'rua alicio clara simeão', 'São Paulo', 'SP', '08160580', true, 120, '2026-03-27 17:37:26.158714', '2026-03-27 17:37:26.158714', 'Mateus Enrico Rocha', '83982402145', 'menrico_rocha@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--
-- Name: empresas_clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.empresas_clientes_id_seq', 24, true);


--
-- PostgreSQL database dump complete
--

