--
-- PostgreSQL database dump
--

-- Dumped from database version 17.8 (a48d9ca)
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: notificacoes; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (1, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1005. Aguarde o link de pagamento.', '{"lote_id": 1005}', NULL, NULL, false, NULL, false, NULL, '2026-02-10 17:22:33.287457', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (2, 'emissao_solicitada_sucesso', 'media', '29930511059', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1007. Aguarde o link de pagamento.', '{"lote_id": 1007}', NULL, NULL, false, NULL, false, NULL, '2026-02-10 19:51:00.173562', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (3, 'emissao_solicitada_sucesso', 'media', '35051737030', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1008. Aguarde o link de pagamento.', '{"lote_id": 1008}', NULL, NULL, false, NULL, false, NULL, '2026-02-11 01:15:06.109694', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (4, 'emissao_solicitada_sucesso', 'media', '64411953056', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1009. Aguarde o link de pagamento.', '{"lote_id": 1009}', NULL, NULL, false, NULL, false, NULL, '2026-02-11 02:02:13.099044', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (5, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1010. Aguarde o link de pagamento.', '{"lote_id": 1010}', NULL, NULL, false, NULL, false, NULL, '2026-02-12 12:32:18.367231', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (6, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1018. Aguarde o link de pagamento.', '{"lote_id": 1018}', NULL, NULL, false, NULL, false, NULL, '2026-02-17 00:23:28.222303', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (7, 'emissao_solicitada_sucesso', 'media', '48538520008', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1026. Aguarde o link de pagamento.', '{"lote_id": 1026}', NULL, NULL, false, NULL, false, NULL, '2026-02-17 13:09:14.535211', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (8, 'emissao_solicitada_sucesso', 'media', '31777317053', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1027. Aguarde o link de pagamento.', '{"lote_id": 1027}', NULL, NULL, false, NULL, false, NULL, '2026-02-17 16:27:58.036474', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (9, 'emissao_solicitada_sucesso', 'media', '29930511059', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1029. Aguarde o link de pagamento.', '{"lote_id": 1029}', NULL, NULL, false, NULL, false, NULL, '2026-02-17 21:35:14.838208', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (10, 'emissao_solicitada_sucesso', 'media', '29930511059', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1025. Aguarde o link de pagamento.', '{"lote_id": 1025}', NULL, NULL, false, NULL, false, NULL, '2026-02-17 23:59:37.428059', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (11, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1019. Aguarde o link de pagamento.', '{"lote_id": 1019}', NULL, NULL, false, NULL, false, NULL, '2026-02-18 01:27:36.591513', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (12, 'emissao_solicitada_sucesso', 'media', '29930511059', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1030. Aguarde o link de pagamento.', '{"lote_id": 1030}', NULL, NULL, false, NULL, false, NULL, '2026-02-18 02:21:21.221813', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (13, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1031. Aguarde o link de pagamento.', '{"lote_id": 1031}', NULL, NULL, false, NULL, false, NULL, '2026-02-18 02:40:40.065771', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (14, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1032. Aguarde o link de pagamento.', '{"lote_id": 1032}', NULL, NULL, false, NULL, false, NULL, '2026-02-18 03:05:53.947524', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (15, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1033. Aguarde o link de pagamento.', '{"lote_id": 1033}', NULL, NULL, false, NULL, false, NULL, '2026-02-18 11:08:59.166885', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (16, 'emissao_solicitada_sucesso', 'media', '04703084945', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1028. Aguarde o link de pagamento.', '{"lote_id": 1028}', NULL, NULL, false, NULL, false, NULL, '2026-02-20 00:08:49.131665', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (17, 'emissao_solicitada_sucesso', 'media', '16911251052', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1034. Aguarde o link de pagamento.', '{"lote_id": 1034}', NULL, NULL, false, NULL, false, NULL, '2026-02-23 21:23:57.211307', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (18, 'emissao_solicitada_sucesso', 'media', '99328531004', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1035. Aguarde o link de pagamento.', '{"lote_id": 1035}', NULL, NULL, false, NULL, false, NULL, '2026-02-23 23:16:38.343661', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (19, 'emissao_solicitada_sucesso', 'media', '79432901009', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1037. Aguarde o link de pagamento.', '{"lote_id": 1037}', NULL, NULL, false, NULL, false, NULL, '2026-02-25 18:39:25.915139', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (20, 'emissao_solicitada_sucesso', 'media', '05248635047', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1039. Aguarde o link de pagamento.', '{"lote_id": 1039}', NULL, NULL, false, NULL, false, NULL, '2026-02-27 13:12:16.205921', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (21, 'emissao_solicitada_sucesso', 'media', '91510815040', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1042. Aguarde o link de pagamento.', '{"lote_id": 1042}', NULL, NULL, false, NULL, false, NULL, '2026-03-03 14:38:37.116556', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (22, 'emissao_solicitada_sucesso', 'media', '69558061069', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1046. Aguarde o link de pagamento.', '{"lote_id": 1046}', NULL, NULL, false, NULL, false, NULL, '2026-03-16 21:49:02.587038', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (23, 'emissao_solicitada_sucesso', 'media', '79432901009', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1049. Aguarde o link de pagamento.', '{"lote_id": 1049}', NULL, NULL, false, NULL, false, NULL, '2026-03-20 11:36:34.721355', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (24, 'emissao_solicitada_sucesso', 'media', '22223287050', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1045. Aguarde o link de pagamento.', '{"lote_id": 1045}', NULL, NULL, false, NULL, false, NULL, '2026-03-24 20:10:24.172199', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (25, 'emissao_solicitada_sucesso', 'media', '87748070997', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1048. Aguarde o link de pagamento.', '{"lote_id": 1048}', NULL, NULL, false, NULL, false, NULL, '2026-03-25 12:25:09.00934', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (26, 'emissao_solicitada_sucesso', 'media', '79432901009', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1051. Aguarde o link de pagamento.', '{"lote_id": 1051}', NULL, NULL, false, NULL, false, NULL, '2026-03-26 18:21:42.893806', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (27, 'emissao_solicitada_sucesso', 'media', '79432901009', 'funcionario', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1052. Aguarde o link de pagamento.', '{"lote_id": 1052}', NULL, NULL, false, NULL, false, NULL, '2026-03-27 18:10:00.300296', NULL, false, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.notificacoes (id, tipo, prioridade, destinatario_cpf, destinatario_tipo, titulo, mensagem, dados_contexto, link_acao, botao_texto, lida, data_leitura, arquivada, contratacao_personalizada_id, criado_em, expira_em, resolvida, data_resolucao, resolvido_por_cpf, clinica_id, data_evento, tomador_tipo) VALUES (28, 'emissao_solicitada_sucesso', 'media', '20192669702', 'gestor', 'Solicitação de emissão enviada', 'Solicitação enviada para lote #1054. Aguarde o link de pagamento.', '{"lote_id": 1054}', NULL, NULL, false, NULL, false, NULL, '2026-03-31 20:01:09.147786', NULL, false, NULL, NULL, NULL, NULL, NULL);


--
-- Name: notificacoes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.notificacoes_id_seq', 28, true);


--
-- PostgreSQL database dump complete
--

