-- Ativar RLS nas tabelas principais
ALTER TABLE funcionarios ENABLE ROW LEVEL SECURITY;

ALTER TABLE avaliacoes ENABLE ROW LEVEL SECURITY;

ALTER TABLE empresas_clientes ENABLE ROW LEVEL SECURITY;

ALTER TABLE clinicas ENABLE ROW LEVEL SECURITY;

ALTER TABLE lotes_avaliacao ENABLE ROW LEVEL SECURITY;

ALTER TABLE laudos ENABLE ROW LEVEL SECURITY;

ALTER TABLE respostas ENABLE ROW LEVEL SECURITY;

ALTER TABLE resultados ENABLE ROW LEVEL SECURITY;

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;