const fs = require('fs');
const path = require('path');

const filePath = path.join(
  __dirname,
  '..',
  'components',
  'admin',
  'PlanosContent.tsx'
);
const oldLines = fs.readFileSync(filePath, 'utf8').split('\n').length;

const lines = [
  "'use client';",
  '',
  "import { Plus, DollarSign } from 'lucide-react';",
  '',
  "import { usePlanosAdmin } from './planos/usePlanosAdmin';",
  "import { PlanoCard } from './planos/PlanoCard';",
  "import { PlanoFormModal } from './planos/PlanoFormModal';",
  "import { PlanoDeleteModal } from './planos/PlanoDeleteModal';",
  '',
  'export function PlanosContent() {',
  '  const {',
  '    planos,',
  '    loading,',
  '    showModal,',
  '    setShowModal,',
  '    editingId,',
  '    formData,',
  '    setFormData,',
  '    closeModal,',
  '    handleSubmit,',
  '    handleEdit,',
  '    showDeleteModal,',
  '    deleteTarget,',
  '    deletePassword,',
  '    setDeletePassword,',
  '    deleteMotivo,',
  '    setDeleteMotivo,',
  '    deleteLoading,',
  '    deleteError,',
  '    handleDelete,',
  '    confirmDelete,',
  '    closeDeleteModal,',
  '  } = usePlanosAdmin();',
  '',
  '  if (loading) {',
  '    return (',
  '      <div className="flex items-center justify-center h-64">',
  '        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-orange-500"></div>',
  '      </div>',
  '    );',
  '  }',
  '',
  '  return (',
  '    <div className="p-6">',
  '      {/* Header */}',
  '      <div className="flex justify-between items-center mb-6">',
  '        <div>',
  '          <h2 className="text-2xl font-bold text-gray-900">',
  '            Gerenciamento de Planos',
  '          </h2>',
  '          <p className="text-sm text-gray-600 mt-1">',
  '            Configure os planos dispon\\u00EDveis para contrata\\u00E7\\u00E3o',
  '          </p>',
  '        </div>',
  '        <button',
  '          onClick={() => setShowModal(true)}',
  '          className="flex items-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors"',
  '        >',
  '          <Plus size={20} />',
  '          Novo Plano',
  '        </button>',
  '      </div>',
  '',
  '      {/* Planos grid */}',
  '      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">',
  '        {planos.map((plano) => (',
  '          <PlanoCard',
  '            key={plano.id}',
  '            plano={plano}',
  '            onEdit={handleEdit}',
  '            onDelete={handleDelete}',
  '          />',
  '        ))}',
  '      </div>',
  '',
  '      {planos.length === 0 && (',
  '        <div className="text-center py-12">',
  '          <DollarSign size={48} className="mx-auto text-gray-300 mb-4" />',
  '          <p className="text-gray-500">Nenhum plano cadastrado</p>',
  '          <p className="text-sm text-gray-400 mt-2">',
  '            Clique em &quot;Novo Plano&quot; para come\\u00E7ar',
  '          </p>',
  '        </div>',
  '      )}',
  '',
  '      {/* Modal de cria\\u00E7\\u00E3o/edi\\u00E7\\u00E3o */}',
  '      {showModal && (',
  '        <PlanoFormModal',
  '          editingId={editingId}',
  '          formData={formData}',
  '          setFormData={setFormData}',
  '          onSubmit={handleSubmit}',
  '          onClose={closeModal}',
  '        />',
  '      )}',
  '',
  '      {/* Modal de exclus\\u00E3o */}',
  '      {showDeleteModal && deleteTarget && (',
  '        <PlanoDeleteModal',
  '          deleteTarget={deleteTarget}',
  '          deletePassword={deletePassword}',
  '          setDeletePassword={setDeletePassword}',
  '          deleteMotivo={deleteMotivo}',
  '          setDeleteMotivo={setDeleteMotivo}',
  '          deleteLoading={deleteLoading}',
  '          deleteError={deleteError}',
  '          onConfirm={confirmDelete}',
  '          onClose={closeDeleteModal}',
  '        />',
  '      )}',
  '    </div>',
  '  );',
  '}',
  '',
];

const content = lines.join('\n');
fs.writeFileSync(filePath, content, 'utf8');
console.log(
  'PlanosContent.tsx rewritten: ' +
    lines.length +
    ' lines (was ' +
    oldLines +
    ')'
);
